// <auto-generated by EnumCreator v1.0 created by gallo>

namespace Game.Enums
{
    [System.Flags]
    public enum Buildings
    {
        Apartment = 1,
        House = 2,
        Condo = 4,
        Hous = 8,
        C = 16,
        Shack = 32,
        Mansio = 64,
        Cardboard_Box = 128,
    }
}
