// <auto-generated>

namespace Game.Enums
{
    public enum Misc
    {
        Default = 1,
        [UnityEngine.Tooltip("Whatever")]
        Something = 2,
        Test = 4,
        asdf = 8,
    }
}
