// <auto-generated>
// Generated by EnumCreator Pro by Nicholas R. Gallo

namespace Game.Enums
{
    public enum Pets
    {
        [UnityEngine.Tooltip("Four legged barker")]
        Dog = 1,
        [UnityEngine.Tooltip("Meow machine")]
        Cat = 2,
        Turtle = 4,
        [UnityEngine.Tooltip("Slow moving creature")]
        Sloth = 8,
    }
}
