// <auto-generated by EnumCreator v1.0 � created by Nick>
// DO NOT EDIT MANUALLY

namespace Game.Enums
{
    [System.Flags]
    public enum Pets
    {
        Dog = 1,
        Cat = 2,
        Fish = 4,
    }
}
