// <auto-generated by EnumCreator v1.0 — created by Nick>
// DO NOT EDIT MANUALLY

namespace Game.Enums
{
    public enum Player
    {
        Ally = 0,
        Enemy = 1,
        Bot = 2,
        _1lkj = 3,
        Bo = 4,
        [System.Obsolete("NPC removed by designer")]
        NPC = 6,
    }
}
