// <auto-generated by EnumCreator v1.0 � created by Nick>

namespace Game.Enums
{
    [System.Flags]
    public enum Weapons
    {
        [UnityEngine.Tooltip("Four legged creature")]
        Dog = 1,
        Cat = 2,
        Fish = 4,
    }
}
